services:
  - type: web
    name: skill-project-tracker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: JDBC_DATABASE_URL
        sync: false
      - key: JDBC_DATABASE_USERNAME
        sync: false
      - key: JDBC_DATABASE_PASSWORD
        sync: false
groq:
  api:
    key: ${GROQ_API_KEY:}

openai:
  api:
    key: ${OPENAI_API_KEY:}
